"""Typed, in-memory view of a dataset (#2), from either schema (#79).

Every detector (#4-#11), the tool layer (#12) and the guard (#14) build on this.
Load rules (see docs/ISSUES.md #2):
- Read every CSV with dtype=str, keep_default_na=False: empty cells stay "", never NaN.
- Convert dates to datetime64 and money/quantities to float64 afterwards.
- Everything else stays str; CLABEs, folio, po_number, account_code must keep
  their leading zeros.
- Never opens anything the agent is not allowed to see.

``load(path)`` accepts three inputs and returns the same :class:`Dataset`:

1. our legacy CSV directory (it has ``suppliers.csv``);
2. a judges' estate as SQLite (``path`` is a file that opens with a ``vendors`` table);
3. a judges' estate as a CSV directory (it has ``vendors.csv``).

The judges' eight tables (``estate_schema.sql``) are adapted onto our frames by the
mapping in ``docs/SPEC_GAP.md``, so the detectors, tools and guard work unchanged on
estates generated by someone else. Two adaptations are worth knowing about:

**Purchase orders stand in for goods receipts.** The judges' schema has no
``goods_receipts`` table; a purchase order is the only deliverable trail it carries.
Each invoice matched to a PO (same vendor, amount within a centavo, PO dated no later
than 30 days after the invoice) gets one synthetic receipt whose ``receipt_id`` is the
``po_id``, so "paid with no deliverable" detectors keep working and any exhibit they
cite resolves to a real ``purchase_orders`` row.

**Payments are linked to invoices by reference, then by amount.** Their ``bank_txns``
has no ``invoice_uuid``: a payment is tied to an invoice by an invoice id appearing in
the ``reference`` text, and failing that by counterparty CLABE plus an exact amount
match on or after the issue date, earliest unpaid invoice first. A payment that
matches nothing keeps an empty ``invoice_uuid`` rather than guessing.

``Dataset.source_format`` says which shape a dataset came from, and
``Dataset.record_table`` maps every record id to the judges' table it lives in, so a
finding's exhibits can name their ``source_table``.
"""
from __future__ import annotations

import json
import sqlite3
import sys
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

DATE_COLUMNS = {
    "suppliers": ["onboarded"],
    "invoices": ["fecha", "fecha_timbrado"],
    "goods_receipts": ["fecha"],
    "bank_transactions": ["fecha"],
    "counterparty_bank": ["fecha"],
    "ledger": ["fecha"],
    "efos_69b": ["fecha_publicacion"],
    "purchase_orders": ["date"],
    "contracts": ["start_date"],
}

FLOAT_COLUMNS = {
    "invoices": ["cantidad", "valor_unitario", "subtotal", "iva", "total"],
    "goods_receipts": ["cantidad"],
    "bank_transactions": ["amount"],
    "counterparty_bank": ["amount"],
    "ledger": ["debit", "credit"],
    "purchase_orders": ["amount"],
    "contracts": ["value"],
}


@dataclass
class Dataset:
    path: Path
    company: dict  # company.json: name, rfc, clabe, city
    suppliers: pd.DataFrame  # supplier_id, name, rfc, street, city, clabe, account_holder, category, onboarded, approved_by, status
    customers: pd.DataFrame  # customer_id, name, rfc, street, city, clabe
    employees: pd.DataFrame  # employee_id, name, rfc, role, home_street, home_city, personal_clabe
    invoices: pd.DataFrame  # uuid, tipo, serie, folio, fecha, fecha_timbrado, rfc_emisor, nombre_emisor, rfc_receptor, nombre_receptor, uso_cfdi, forma_pago, metodo_pago, clave_prod_serv, descripcion, cantidad, valor_unitario, subtotal, iva, total, moneda, po_number, counterparty_id, approved_by
    goods_receipts: pd.DataFrame  # receipt_id, po_number, supplier_id, invoice_uuid, fecha, descripcion, cantidad, received_by, warehouse
    bank_transactions: pd.DataFrame  # txn_id, fecha, account_clabe, direction, amount, counterparty_name, counterparty_clabe, reference, invoice_uuid
    counterparty_bank: pd.DataFrame  # record_id, entity_name, entity_clabe, fecha, direction, amount, counterparty_name, counterparty_clabe, reference
    ledger: pd.DataFrame  # entry_id, fecha, account_code, account_name, debit, credit, descripcion, invoice_uuid, txn_id
    efos_69b: pd.DataFrame  # rfc, nombre, situacion, fecha_publicacion
    # Judges'-schema tables with no legacy equivalent; empty on a legacy load.
    purchase_orders: pd.DataFrame = field(default_factory=lambda: _empty_frame("purchase_orders"))
    contracts: pd.DataFrame = field(default_factory=lambda: _empty_frame("contracts"))
    # record id -> the judges' table it lives in, for a finding's exhibits.
    record_table: dict[str, str] = field(default_factory=dict)
    source_format: str = "legacy"  # "legacy" | "judges"

    def all_record_ids(self) -> set[str]:
        """Invoice uuids | txn_ids | counterparty record_ids | receipt_ids | PO | contract ids."""
        ids: set[str] = set(self.invoices["uuid"])
        ids.update(self.bank_transactions["txn_id"])
        ids.update(self.counterparty_bank["record_id"])
        ids.update(self.goods_receipts["receipt_id"])
        ids.update(self.purchase_orders["po_id"])
        ids.update(self.contracts["contract_id"])
        return ids

    def all_entity_ids(self) -> set[str]:
        """supplier_ids | customer_ids | employee_ids."""
        ids: set[str] = set(self.suppliers["supplier_id"])
        ids.update(self.customers["customer_id"])
        ids.update(self.employees["employee_id"])
        return ids


def _read_csv(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, dtype=str, keep_default_na=False, encoding="utf-8")


def _convert(df: pd.DataFrame, stem: str, *, coerce: bool = False) -> pd.DataFrame:
    """Type the date and money columns of one frame.

    ``coerce`` is for estates we did not write: an unparseable date becomes NaT and a
    blank amount becomes 0.0 instead of raising. Our own CSVs stay strict, so a
    generator that starts emitting malformed dates fails loudly.
    """
    df = df.copy()
    for col in DATE_COLUMNS.get(stem, []):
        parsed = pd.to_datetime(df[col], errors="coerce") if coerce else pd.to_datetime(df[col])
        df[col] = parsed.astype("datetime64[ns]")
    for col in FLOAT_COLUMNS.get(stem, []):
        if coerce:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0.0).astype("float64")
        else:
            df[col] = df[col].astype("float64")
    return df


def load(path: str | Path) -> Dataset:
    """Load a legacy directory, a judges' ``.db`` or a judges' CSV directory."""
    root = Path(path)
    if root.is_dir() and (root / "suppliers.csv").exists():
        return _load_legacy(root)
    if root.is_file():
        return _from_judges(_read_judges_db(root), root)
    if root.is_dir() and (root / "vendors.csv").exists():
        return _from_judges(_read_judges_csv(root), root)
    raise FileNotFoundError(
        f"{root} is not a dataset: expected suppliers.csv (legacy), vendors.csv "
        f"(judges' CSV export) or a judges' SQLite estate"
    )


def _load_legacy(root: Path) -> Dataset:
    """Our own CSV layout, unchanged since #2."""
    frames: dict[str, pd.DataFrame] = {}
    for stem in (
        "suppliers",
        "customers",
        "employees",
        "invoices",
        "goods_receipts",
        "bank_transactions",
        "counterparty_bank",
        "ledger",
        "efos_69b",
    ):
        df = _read_csv(root / f"{stem}.csv")
        frames[stem] = _convert(df, stem)
    company = json.loads((root / "company.json").read_text(encoding="utf-8"))
    return Dataset(path=root, company=company, **frames)


# ----------------------------------------------------------- judges' estate (#79)
# estate_schema.sql, table by table. A table missing from an estate loads empty
# rather than failing: a clean-books estate has no efos_list, and not every
# generator writes contracts.
JUDGE_COLUMNS: dict[str, list[str]] = {
    "vendors": ["rfc", "legal_name", "registered_date", "address", "bank_clabe", "category", "contact_email"],
    "invoices": [
        "uuid", "issuer_rfc", "receiver_rfc", "issue_date", "subtotal", "iva", "total",
        "concepto_text", "uso_cfdi", "forma_pago", "metodo_pago", "status",
    ],
    "ledger": [
        "entry_id", "date", "account_code", "account_name", "debit", "credit",
        "description", "invoice_uuid", "cost_center", "approver",
    ],
    "bank_txns": ["txn_id", "date", "from_clabe", "to_clabe", "amount", "reference", "channel"],
    "purchase_orders": ["po_id", "vendor_rfc", "date", "amount", "requester", "approver", "description"],
    "contracts": ["contract_id", "vendor_rfc", "start_date", "value", "scope_text"],
    "employees": ["emp_id", "name", "role", "bank_clabe", "hire_date"],
    "efos_list": ["rfc", "legal_name", "status", "publication_date"],
}

PURCHASE_ORDER_COLUMNS = JUDGE_COLUMNS["purchase_orders"]
CONTRACT_COLUMNS = JUDGE_COLUMNS["contracts"]

SUPPLIER_COLUMNS = [
    "supplier_id", "name", "rfc", "street", "city", "clabe", "account_holder",
    "category", "onboarded", "approved_by", "status",
]
CUSTOMER_COLUMNS = ["customer_id", "name", "rfc", "street", "city", "clabe"]
EMPLOYEE_COLUMNS = ["employee_id", "name", "rfc", "role", "home_street", "home_city", "personal_clabe"]
INVOICE_COLUMNS = [
    "uuid", "tipo", "serie", "folio", "fecha", "fecha_timbrado", "rfc_emisor", "nombre_emisor",
    "rfc_receptor", "nombre_receptor", "uso_cfdi", "forma_pago", "metodo_pago", "clave_prod_serv",
    "descripcion", "cantidad", "valor_unitario", "subtotal", "iva", "total", "moneda",
    "po_number", "counterparty_id", "approved_by", "status",
]
GOODS_RECEIPT_COLUMNS = [
    "receipt_id", "po_number", "supplier_id", "invoice_uuid", "fecha", "descripcion",
    "cantidad", "received_by", "warehouse",
]
BANK_COLUMNS = [
    "txn_id", "fecha", "account_clabe", "direction", "amount", "counterparty_name",
    "counterparty_clabe", "reference", "invoice_uuid", "channel",
]
COUNTERPARTY_COLUMNS = [
    "record_id", "entity_name", "entity_clabe", "fecha", "direction", "amount",
    "counterparty_name", "counterparty_clabe", "reference",
]
LEDGER_COLUMNS = [
    "entry_id", "fecha", "account_code", "account_name", "debit", "credit",
    "descripcion", "invoice_uuid", "txn_id", "cost_center", "approver",
]
EFOS_COLUMNS = ["rfc", "nombre", "situacion", "fecha_publicacion"]

# A purchase order may be raised up to this long after the invoice it settles and
# still be the deliverable trail for it (late paperwork is normal; a PO that never
# appears is the signal a detector is looking for).
PO_WINDOW_DAYS = 30

_WARNED: set[str] = set()


def _warn_once(message: str) -> None:
    """Say something about a malformed estate once per process, never raise."""
    if message not in _WARNED:
        _WARNED.add(message)
        print(f"agent.data: {message}", file=sys.stderr)


def _as_text(value) -> str:
    """SQLite value -> the string the CSV reader would have produced; NULL/NaN -> ""."""
    if value is None:
        return ""
    if isinstance(value, float) and value != value:  # NaN
        return ""
    if isinstance(value, bytes):
        return value.decode("utf-8", "replace")
    return str(value)


def _empty(columns: list[str]) -> pd.DataFrame:
    return pd.DataFrame({c: pd.Series(dtype="object") for c in columns})


def _empty_frame(stem: str) -> pd.DataFrame:
    """An empty frame with the right columns *and* the right dtypes for ``stem``."""
    return _convert(_empty(JUDGE_COLUMNS[stem]), stem, coerce=True)


def _frame(rows: list[dict], columns: list[str]) -> pd.DataFrame:
    """Build a frame with exactly ``columns``, string-typed, from row dicts."""
    if not rows:
        return pd.DataFrame({c: pd.Series([], dtype="object") for c in columns})
    return pd.DataFrame([{c: row.get(c, "") for c in columns} for row in rows], columns=columns)


def _stringify(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    """Every declared column as text, in schema order; undeclared columns dropped."""
    out: dict[str, list[str]] = {}
    for col in columns:
        out[col] = [_as_text(v) for v in df[col]] if col in df.columns else [""] * len(df)
    return pd.DataFrame(out, columns=columns)


def _read_judges_db(path: Path) -> dict[str, pd.DataFrame]:
    """Read the eight tables out of a judges' SQLite estate, read-only."""
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    try:
        try:
            names = {r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        except sqlite3.DatabaseError as exc:
            raise FileNotFoundError(f"{path} is not a SQLite estate: {exc}") from exc
        if "vendors" not in names:
            raise FileNotFoundError(f"{path} has no 'vendors' table; not a judges' estate")
        frames = {}
        for table, columns in JUDGE_COLUMNS.items():
            if table in names:
                frames[table] = _stringify(pd.read_sql_query(f"SELECT * FROM {table}", conn), columns)
            else:
                _warn_once(f"{path}: no '{table}' table; loading it empty")
                frames[table] = _empty(columns)
        return frames
    finally:
        conn.close()


def _read_judges_csv(root: Path) -> dict[str, pd.DataFrame]:
    """Read the eight tables out of a judges' CSV export."""
    frames = {}
    for table, columns in JUDGE_COLUMNS.items():
        csv_path = root / f"{table}.csv"
        if csv_path.exists():
            frames[table] = _stringify(_read_csv(csv_path), columns)
        else:
            _warn_once(f"{root}: no {table}.csv; loading it empty")
            frames[table] = _empty(columns)
    return frames


def _mode(values) -> str:
    """Most common non-empty value; first-seen wins a tie. "" when there is none."""
    counts: dict[str, int] = {}
    for value in values:
        if value:
            counts[value] = counts.get(value, 0) + 1
    if not counts:
        return ""
    return max(counts, key=lambda k: counts[k])


def _dates(series: pd.Series, label: str) -> list[pd.Timestamp]:
    """Parse a date column; unparseable non-empty values become NaT and are logged once."""
    parsed = pd.to_datetime(series, errors="coerce")
    bad = sum(1 for raw, value in zip(series, parsed) if raw and pd.isna(value))
    if bad:
        _warn_once(f"{label}: {bad} date(s) could not be parsed; they are NaT")
    return list(parsed)


def _floats(series: pd.Series) -> list[float]:
    return [float(v) for v in pd.to_numeric(series, errors="coerce").fillna(0.0)]


def _invoice_in_reference(reference: str, uuids: set[str], uuid_list: list[str]) -> str:
    """The invoice id named by a payment reference, or ""; tokens first, then substrings."""
    if not reference:
        return ""
    token = ""
    current: list[str] = []
    for char in reference:
        if char.isalnum() or char == "-":
            current.append(char)
        else:
            token = "".join(current)
            if token and token in uuids:
                return token
            current = []
    token = "".join(current)
    if token and token in uuids:
        return token
    for uuid in uuid_list:
        if uuid and uuid in reference:
            return uuid
    return ""


def _from_judges(frames: dict[str, pd.DataFrame], path: Path) -> Dataset:
    """Adapt the judges' eight tables onto our frames (docs/SPEC_GAP.md)."""
    vendors = frames["vendors"]
    judge_invoices = frames["invoices"]
    judge_ledger = frames["ledger"]
    judge_bank = frames["bank_txns"]
    judge_pos = frames["purchase_orders"]
    judge_contracts = frames["contracts"]
    judge_employees = frames["employees"]
    judge_efos = frames["efos_list"]

    vendor_by_rfc = {row["rfc"]: row for row in vendors.to_dict("records") if row["rfc"]}
    vendor_clabes = {row["bank_clabe"]: row["rfc"] for row in vendor_by_rfc.values() if row["bank_clabe"]}

    # --- company identity: the party every vendor invoices, paying from one account.
    company_rfc = _mode(
        receiver
        for issuer, receiver in zip(judge_invoices["issuer_rfc"], judge_invoices["receiver_rfc"])
        if issuer in vendor_by_rfc
    )
    company_clabe = _mode(
        sender
        for sender, target in zip(judge_bank["from_clabe"], judge_bank["to_clabe"])
        if target in vendor_clabes
    )
    company = {"name": company_rfc, "rfc": company_rfc, "clabe": company_clabe, "city": ""}

    # --- employees; their names are how POs and the ledger spell an approver.
    employees = _frame(
        [
            {
                "employee_id": row["emp_id"],
                "name": row["name"],
                "rfc": "",
                "role": row["role"],
                "home_street": "",
                "home_city": "",
                "personal_clabe": row["bank_clabe"],
            }
            for row in judge_employees.to_dict("records")
        ],
        EMPLOYEE_COLUMNS,
    )
    emp_id_by_name = {row["name"]: row["emp_id"] for row in judge_employees.to_dict("records") if row["name"]}

    # --- purchase orders, matched to the invoices they settle.
    po_rows = judge_pos.to_dict("records")
    po_dates = _dates(judge_pos["date"], f"{path}:purchase_orders.date")
    po_amounts = _floats(judge_pos["amount"])
    for row, when, amount in zip(po_rows, po_dates, po_amounts):
        row["_date"], row["_amount"] = when, amount

    invoice_rows = judge_invoices.to_dict("records")
    invoice_dates = _dates(judge_invoices["issue_date"], f"{path}:invoices.issue_date")
    invoice_totals = _floats(judge_invoices["total"])
    for row, when, total in zip(invoice_rows, invoice_dates, invoice_totals):
        row["_date"], row["_total"] = when, total

    by_po_order = sorted(po_rows, key=lambda r: (r["_date"] is pd.NaT, r["_date"], r["po_id"]))
    claimed: set[str] = set()
    po_for_invoice: dict[str, dict] = {}
    for invoice in sorted(invoice_rows, key=lambda r: (r["_date"] is pd.NaT, r["_date"], r["uuid"])):
        if invoice["issuer_rfc"] not in vendor_by_rfc:
            continue  # a sale: the company issued it, so no purchase order exists
        for po in by_po_order:
            if po["po_id"] in claimed or po["vendor_rfc"] != invoice["issuer_rfc"]:
                continue
            if abs(po["_amount"] - invoice["_total"]) > 0.01:
                continue
            if pd.isna(po["_date"]) or pd.isna(invoice["_date"]):
                continue
            if po["_date"] > invoice["_date"] + pd.Timedelta(days=PO_WINDOW_DAYS):
                continue
            claimed.add(po["po_id"])
            po_for_invoice[invoice["uuid"]] = po
            break

    # --- suppliers: a vendor is approved by whoever signs off most of its POs.
    approvers: dict[str, list[str]] = {}
    for po in po_rows:
        approvers.setdefault(po["vendor_rfc"], []).append(po["approver"])
    suppliers = _frame(
        [
            {
                "supplier_id": "RFC:" + row["rfc"],
                "name": row["legal_name"],
                "rfc": row["rfc"],
                "street": row["address"],
                "city": "",
                "clabe": row["bank_clabe"],
                "account_holder": row["legal_name"],
                "category": row["category"],
                "onboarded": row["registered_date"],
                "approved_by": emp_id_by_name.get(_mode(approvers.get(row["rfc"], [])), ""),
                "status": "activo",
            }
            for row in vendors.to_dict("records")
        ],
        SUPPLIER_COLUMNS,
    )

    # --- the ledger's own approver, as a fallback for who signed an invoice off.
    ledger_rows = judge_ledger.to_dict("records")
    ledger_approver: dict[str, str] = {}
    for row in ledger_rows:
        uuid = row["invoice_uuid"]
        if uuid and row["approver"] and uuid not in ledger_approver:
            ledger_approver[uuid] = row["approver"]

    # --- invoices.
    invoices = _frame(
        [
            {
                "uuid": row["uuid"],
                "tipo": "recibida" if row["receiver_rfc"] == company_rfc else "emitida",
                "serie": "",
                "folio": "",
                "fecha": row["issue_date"],
                "fecha_timbrado": row["issue_date"],
                "rfc_emisor": row["issuer_rfc"],
                "nombre_emisor": vendor_by_rfc.get(row["issuer_rfc"], {}).get("legal_name", ""),
                "rfc_receptor": row["receiver_rfc"],
                "nombre_receptor": vendor_by_rfc.get(row["receiver_rfc"], {}).get("legal_name", ""),
                "uso_cfdi": row["uso_cfdi"],
                "forma_pago": row["forma_pago"],
                "metodo_pago": row["metodo_pago"],
                "clave_prod_serv": "",
                "descripcion": row["concepto_text"],
                "cantidad": "1.0",
                "valor_unitario": row["subtotal"],
                "subtotal": row["subtotal"],
                "iva": row["iva"],
                "total": row["total"],
                "moneda": "MXN",
                "po_number": po_for_invoice.get(row["uuid"], {}).get("po_id", ""),
                "counterparty_id": "RFC:"
                + (row["issuer_rfc"] if row["receiver_rfc"] == company_rfc else row["receiver_rfc"]),
                "approved_by": emp_id_by_name.get(
                    po_for_invoice.get(row["uuid"], {}).get("approver", ""),
                    emp_id_by_name.get(ledger_approver.get(row["uuid"], ""), ""),
                ),
                "status": row["status"],
            }
            for row in invoice_rows
        ],
        INVOICE_COLUMNS,
    )

    # --- goods receipts: the PO is the only deliverable trail the schema carries.
    goods_receipts = _frame(
        [
            {
                "receipt_id": po["po_id"],
                "po_number": po["po_id"],
                "supplier_id": "RFC:" + po["vendor_rfc"],
                "invoice_uuid": uuid,
                "fecha": po["date"],
                "descripcion": po["description"],
                "cantidad": "1.0",
                "received_by": emp_id_by_name.get(po["approver"], po["approver"]),
                "warehouse": "",
            }
            for uuid, po in sorted(po_for_invoice.items(), key=lambda kv: kv[1]["po_id"])
        ],
        GOODS_RECEIPT_COLUMNS,
    )

    # --- bank: the company's own legs, and the third-party legs between others.
    bank_rows = judge_bank.to_dict("records")
    bank_dates = _dates(judge_bank["date"], f"{path}:bank_txns.date")
    bank_amounts = _floats(judge_bank["amount"])
    for row, when, amount in zip(bank_rows, bank_dates, bank_amounts):
        row["_date"], row["_amount"] = when, amount

    name_by_clabe = {row["bank_clabe"]: row["legal_name"] for row in vendor_by_rfc.values() if row["bank_clabe"]}
    name_by_clabe.update(
        {row["bank_clabe"]: row["name"] for row in judge_employees.to_dict("records") if row["bank_clabe"]}
    )

    uuid_set = {row["uuid"] for row in invoice_rows if row["uuid"]}
    uuid_list = [row["uuid"] for row in invoice_rows if row["uuid"]]
    invoice_by_uuid = {row["uuid"]: row for row in invoice_rows}

    company_legs = [
        row for row in bank_rows if company_clabe and company_clabe in (row["from_clabe"], row["to_clabe"])
    ]
    own = {row["txn_id"] for row in company_legs}
    third_party = [row for row in bank_rows if row["txn_id"] not in own]

    # Pass A: a reference that names an invoice is the payment's own word for it.
    linked: dict[str, str] = {}
    paid: set[str] = set()
    for row in company_legs:
        uuid = _invoice_in_reference(row["reference"], uuid_set, uuid_list)
        if uuid:
            linked[row["txn_id"]] = uuid
            paid.add(uuid)

    # Customers bank wherever the money for their invoices came from.
    customer_clabes: dict[str, list[str]] = {}
    for row in company_legs:
        uuid = linked.get(row["txn_id"], "")
        if not uuid or row["to_clabe"] != company_clabe:
            continue
        invoice = invoice_by_uuid.get(uuid, {})
        if invoice.get("receiver_rfc") and invoice["receiver_rfc"] != company_rfc:
            customer_clabes.setdefault(invoice["receiver_rfc"], []).append(row["from_clabe"])
    rfc_by_clabe = dict(vendor_clabes)
    for rfc, clabes in customer_clabes.items():
        chosen = _mode(clabes)
        if chosen:
            rfc_by_clabe.setdefault(chosen, rfc)

    # Pass B: no reference, so the counterparty's account plus an exact amount.
    for row in sorted(company_legs, key=lambda r: (r["_date"] is pd.NaT, r["_date"], r["txn_id"])):
        if row["txn_id"] in linked:
            continue
        other = row["to_clabe"] if row["from_clabe"] == company_clabe else row["from_clabe"]
        counterparty = rfc_by_clabe.get(other, "")
        if not counterparty:
            continue
        candidates = [
            inv
            for inv in invoice_rows
            if inv["uuid"] not in paid
            and counterparty in (inv["issuer_rfc"], inv["receiver_rfc"])
            and inv["issuer_rfc"] != inv["receiver_rfc"]
            and abs(inv["_total"] - row["_amount"]) <= 0.01
            and not pd.isna(inv["_date"])
            and not pd.isna(row["_date"])
            and row["_date"] >= inv["_date"]
        ]
        if candidates:
            chosen = min(candidates, key=lambda inv: (inv["_date"], inv["uuid"]))
            linked[row["txn_id"]] = chosen["uuid"]
            paid.add(chosen["uuid"])

    bank_transactions = _frame(
        [
            {
                "txn_id": row["txn_id"],
                "fecha": row["date"],
                "account_clabe": company_clabe,
                "direction": "out" if row["from_clabe"] == company_clabe else "in",
                "amount": row["amount"],
                "counterparty_name": name_by_clabe.get(
                    row["to_clabe"] if row["from_clabe"] == company_clabe else row["from_clabe"], ""
                ),
                "counterparty_clabe": row["to_clabe"] if row["from_clabe"] == company_clabe else row["from_clabe"],
                "reference": row["reference"],
                "invoice_uuid": linked.get(row["txn_id"], ""),
                "channel": row["channel"],
            }
            for row in company_legs
        ],
        BANK_COLUMNS,
    )

    counterparty_bank = _frame(
        [
            {
                "record_id": row["txn_id"],
                "entity_name": name_by_clabe.get(row["from_clabe"], ""),
                "entity_clabe": row["from_clabe"],
                "fecha": row["date"],
                "direction": "out",
                "amount": row["amount"],
                "counterparty_name": name_by_clabe.get(row["to_clabe"], ""),
                "counterparty_clabe": row["to_clabe"],
                "reference": row["reference"],
            }
            for row in third_party
        ],
        COUNTERPARTY_COLUMNS,
    )

    # --- customers: whoever the company invoices.
    customers = _frame(
        [
            {
                "customer_id": "RFC:" + rfc,
                "name": vendor_by_rfc.get(rfc, {}).get("legal_name", ""),
                "rfc": rfc,
                "street": "",
                "city": "",
                "clabe": _mode(customer_clabes.get(rfc, [])),
            }
            for rfc in sorted(
                {
                    row["receiver_rfc"]
                    for row in invoice_rows
                    if row["receiver_rfc"] and row["receiver_rfc"] != company_rfc
                }
            )
        ],
        CUSTOMER_COLUMNS,
    )

    ledger = _frame(
        [
            {
                "entry_id": row["entry_id"],
                "fecha": row["date"],
                "account_code": row["account_code"],
                "account_name": row["account_name"],
                "debit": row["debit"],
                "credit": row["credit"],
                "descripcion": row["description"],
                "invoice_uuid": row["invoice_uuid"],
                "txn_id": "",
                "cost_center": row["cost_center"],
                "approver": row["approver"],
            }
            for row in ledger_rows
        ],
        LEDGER_COLUMNS,
    )

    efos_69b = _frame(
        [
            {
                "rfc": row["rfc"],
                "nombre": row["legal_name"],
                "situacion": row["status"].strip().capitalize(),
                "fecha_publicacion": row["publication_date"],
            }
            for row in judge_efos.to_dict("records")
        ],
        EFOS_COLUMNS,
    )

    # --- which table every citable record came out of.
    record_table: dict[str, str] = {}
    for uuid in uuid_list:
        record_table[uuid] = "invoices"
    for row in bank_rows:
        if row["txn_id"]:
            record_table[row["txn_id"]] = "bank_txns"
    for row in ledger_rows:
        if row["entry_id"]:
            record_table[row["entry_id"]] = "ledger"
    for row in judge_contracts.to_dict("records"):
        if row["contract_id"]:
            record_table[row["contract_id"]] = "contracts"
    for row in judge_efos.to_dict("records"):
        if row["rfc"]:
            record_table[row["rfc"]] = "efos_list"
    for row in judge_employees.to_dict("records"):
        if row["emp_id"]:
            record_table[row["emp_id"]] = "employees"
    for row in po_rows:
        if row["po_id"]:
            record_table[row["po_id"]] = "purchase_orders"
    for rfc in vendor_by_rfc:  # a vendor on the 69-B list is still a vendors row
        record_table[rfc] = "vendors"

    frames_out = {
        "suppliers": suppliers,
        "customers": customers,
        "employees": employees,
        "invoices": invoices,
        "goods_receipts": goods_receipts,
        "bank_transactions": bank_transactions,
        "counterparty_bank": counterparty_bank,
        "ledger": ledger,
        "efos_69b": efos_69b,
        "purchase_orders": _stringify(judge_pos, PURCHASE_ORDER_COLUMNS),
        "contracts": _stringify(judge_contracts, CONTRACT_COLUMNS),
    }
    converted = {stem: _convert(df, stem, coerce=True) for stem, df in frames_out.items()}
    return Dataset(
        path=path,
        company=company,
        record_table=record_table,
        source_format="judges",
        **converted,
    )
